1.Write a NumPy program to create a 3x3x3 array filled with arbitrary values

In [4]:
import numpy as np
y=np.random.random((3,3,3))
print(y)

[[[2.35124038e-01 7.72952380e-01 8.04724701e-01]
  [8.05867098e-01 4.01136247e-01 3.02521942e-01]
  [6.82353395e-02 7.94111022e-01 1.98249663e-01]]

 [[3.04224013e-01 6.01843557e-04 8.72024327e-01]
  [5.12628081e-01 9.01965802e-01 7.65856537e-01]
  [6.53461549e-02 6.13463531e-01 7.75533489e-01]]

 [[2.56488924e-01 1.48843920e-01 9.06777150e-01]
  [4.11113613e-02 2.47636967e-01 2.98895988e-02]
  [2.50988305e-01 6.94166723e-01 3.15945511e-01]]]


2.Write a NumPy program to create a vector with values ​​ranging from 15 to 55 and print all values ​​except the first and last.

In [12]:
v = np.arange(15,56)
print("The original vector is:")
print(v)
print("All values except he first and last of the vector :")
print(v[1:-1])

The original vector is:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
All values except he first and last of the vector :
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


3.Write a NumPy program to multiply two given arrays of the 2 x 3 size element-by-element. 

In [24]:
arr1=np.array([[2,6,8],[3,5,7]])
arr2=np.array([[1,3,4],[8,9,4]])
print("First Array:")
print(arr1)
print("Second Array:")
print(arr2)
print("After multiplying the two arrays:")
print(np.multiply(arr1,arr2))


First Array:
[[2 6 8]
 [3 5 7]]
Second Array:
[[1 3 4]
 [8 9 4]]
After multiplying the two arrays:
[[ 2 18 32]
 [24 45 28]]


4.Write a NumPy program to create a 3X4 array and iterate over it

In [25]:
b=np.arange(1,13).reshape((3,4))
print("Original array is:")
print(b)
print("Each element of array is")
for x in np.nditer(b):
    print(x,end=" ")


Original array is:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Each element of array is
1 2 3 4 5 6 7 8 9 10 11 12 

5.Write a NumPy program to compute the sum of the diagonal element(Trace of array) of a given array(4x4). (use built in linear algebra function only) 

In [26]:
arr=np.arange(1,17).reshape(4,4)
print("Original array is:\n")
print(arr)
tr=np.trace(arr)
print("Trace of the array is")
print(tr)

Original array is:

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Trace of the array is
34


#### NOTE : 
Submit the notebook file with name : 2kxx-CSE-xx_your name

questions containing "given array" declare the array and give appropriate values 